export const ROUTES = {
  root: '/',
  login: '/login',
  dashboard: '/dashboard',
  users: '/users',
  products: '/products',
  brands: '/brands',
  productCreate: '/products/create',
  productEdit: '/products/:productId/edit',
  categories: '/categories',
  ads: '/ads',
  orders: '/orders',
  deliveryFinance: '/delivery-finance',
  notifications: '/notifications',
  otpAdmin: '/otp-whatsapp',
  settings: '/settings',
  settingsPricing: '/settings/pricing',
  settingsPreferences: '/settings/preferences',
  unauthorized: '/unauthorized',
} as const;
